theme: jekyll-theme-architect

title: HK2 - Dependency Injection Kernel
description: A light-weight and dynamic dependency injection framework

# sidebar links url
links:
  download: http://repo1.maven.org/maven2/org/glassfish/hk2/
  source: https://github.com/javaee/hk2
  mailinglist: https://javaee.groups.io/g/hk2
  #javadocs:
  #docs:
  #faq:
  #hide_issuetracker: true #set explicitly to 'true' if you don't want to have the issue tracker link displayed

gems:
  - jekyll-sitemap
